#ifndef __COMPONENTS_INC_HEADER_GUARD__
#define __COMPONENTS_INC_HEADER_GUARD__

#include <iostream> // std::cout, std::cerr, std::cin
#include <fstream> // std::ofstream, std::ifstream
#include <string> // std::string, std::getline
#include <cstdlib> // free
#include <brainfcxx.hh> // BF::Interpreter, BF::Exception, BF::word,
                        // BF::i8, BF::i16, BF::i32, BF::i64,
                        // BF::ui8, BF::ui16, BF::ui32, BF::ui64

#endif // __COMPONENTS_INC_HEADER_GUARD__
